source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
includes_dir: ./_includes

collections:
  articles:
    output: true
    permanlink: /aticles/:path/

defaults:
  -
    scope:
      path: ''
      type: articles
    values:
      layout: article

safe: false
include: []
exclude:
  - README.md
  - node_modules
  - .gitignore
  - package.json
  - deploy.json
  - Gruntfile.coffee
keep_files:
encoding: 'utf-8'

# conversion
markdown: kramdown
