source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
includes_dir: ./_includes

collections:
  articles:
    output: true
    permanlink: /aticles/:path/

defaults:
  -
    scope:
      path: ''
      type: articles
    values:
      layout: article

safe: false
include: []
exclude:
  - README.md
  - node_modules
  - .gitignore
  - package.json
  - deploy.json
  - Gruntfile.coffee
keep_files:
encoding: 'utf-8'

# plugins
# gems:
# github  - jekyll-sass-converter

# conversion
markdown: kramdown

# serving
port: 4000
host: 127.0.0.1
baseurl: '' # does not include hostname

# outputting

sass:
  # style: :compressed
  sass_dir: assets/css/_scss
